### ISSUE TITLE
Privacy Policy Clickwrap Agreement Page Layout

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#108]
Privacy policy agreement page for registration, with:
- forced scrolling through privacy policy
- Check box that says "I have read the privacy policy agreement"
- hyperlink to privacy policy page
- Decline button
- Accept button

**Comment by levis501** [comment]
This was mostly complete except for a bug in calculation when the scroll reaches the bottom, and the hyperlink to the document.
