### ISSUE TITLE
Terms of Service Clickwrap Agreement Page Layout

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#109]
Terms of Service clickwrap agreement for registration, with:
- Forced scrolling of Terms of Service
- check box that says "I have read the Terms of Service"
- Hyperlink to Terms of Service Page
- Decline button
- Accept button

**Comment by levis501** [comment]
This was mostly complete except for a bug in calculation when the scroll reaches the bottom, and the hyperlink to the document.
