### ISSUE TITLE
Password Reset Page Layout

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#12]
Password reset page:

- Field for entering a new password
- Field for confirming new password
- Submit button

**Comment by levis501** [comment]
I'd like to take this one on... started working on it as an example at Transcode today

**Comment by hexixt** [comment]
@levis501 the page is yours to code. I will assign the issue to you

**Comment by levis501** [comment]
This has already been implemented as of https://github.com/TransgenderHousingRelief/TransgenderHousingRelief/commit/b9b57a11  . Nice work @turtles !
