### ISSUE TITLE
Housing Resources Page Layout

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#15]
Links to housing resources
User submitted housing resources feeds by state

**Comment by levis501** [comment]
Initial page complete as of https://github.com/TransgenderHousingRelief/TransgenderHousingRelief/pull/59

I haven't implemented user-submitted housing resources, or filtering.
For user submissions, I think we'll need a database.  For both user submissions and filtering, layouts would be helpful.
