### ISSUE TITLE
Submit Wanted Ad Page Layout

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#20]
Submit wanted ad page:

- Fields for:
  - Title
  - Message
  - Location (state, city all for both) field
  - Location (state, city, all for both) selected field
  - Miles within drop down
  - Arrow buttons to move states and cities from one field to another [if unselected, default to showing up in all searches]
  - Tags (all from advanced search)
  - Dates fields (optional)

**Comment by turtles** [comment]
No longer needed: Submit Ad Page is used for both wanted and offered ad submission.
