### ISSUE TITLE
Legal Resources Searchable By State Dropdown

### ISSUE THREAD

**Issue by hexixt** [TransgenderHousingRelief/TransgenderHousingRelief#89]

**Comment by levis501** [comment]
Since we don't currently have legal resources specific to every state, I thought it best to stick with the tag filtering.  If you'd still prefer the state dropdown, lmk and I'll swap out the tag filter for a state dropdown -- it's nbd to switch it

**Comment by turtles** [comment]
I like how you've implemented it, stateless and using the router, because you can link to the filtered results.
